theme = "catppuccin_mocha"

[editor.file-picker]
hidden = false

[editor]
bufferline = "always"
mouse = false
middle-click-paste=false
completion-replace=true
trim-final-newlines=true
trim-trailing-whitespace=true
