[language-server.vtsls]
command = "vtsls"
args = ["--stdio"]
[language-server.vtsls.config.typescript.preferences]
importModuleSpecifier = "non-relative"

[language-server.rust-analyzer]
config.check.command = "clippy"

[[language]]
name = "tsx"
auto-format = true
language-servers = [ "vtsls" ]

[[language]]
name = "typescript"
auto-format = true
language-servers = [ "vtsls" ]

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "go"
auto-format = true
